/* eslint-disable camelcase */
export type Cj = {
  id?: number
  id_andamentocoger: number
  id_andamento: number
  id_motivoconselho: number
  id_decorrenciaconselho: number
  id_situacaoconselho: number
  motivo_outros: string
  cdopm: string
  sjd_ref: number
  sjd_ref_ano: number
  abertura_data: Date
  fato_data: Date
  libelo_file: string
  doc_tipo: string
  doc_numero: string
  portaria_numero: string
  portaria_data: Date
  parecer_file: string
  decisao_file: string
  doc_prorrogacao: string
  numero_tj: string
  prescricao_data: Date
  exclusao_text: string
  rec_ato_file: string
  rec_gov_file: string
  opm_meta4: string
  ac_desempenho_bl: string
  ac_conduta_bl: string
  ac_honra_bl: string
  tjpr_file: string
  sjd_file: string
  sintese_text: string
  prioridade: boolean
  completo: boolean
  outromotivo: string
  createdAt?: Date
  updatedAt?: Date
  deletedAt?: Date
}
