/* eslint-disable camelcase */
export type Envolvido = {
  id?: number
  rg_substituto: string
  nome: string
  rg: string
  situacao: string
  cargo: string
  resultado: string
  inclusao_ano: number
  ipm_julgamento: string
  ipm_processocrime: string
  ipm_pena_anos: number
  ipm_pena_meses: number
  ipm_pena_dias: number
  ipm_tipodapena: string
  ipm_transitojulgado_bl: string
  ipm_restritiva_bl: string
  obs_txt: string
  exclusaoportaria_data: Date
  exclusaoportaria_numero: string
  exclusaoboletim: string
  exclusaobg_numero: number
  exclusaobg_ano: number
  exclusaobg_data: Date
  exclusaoopm: string
  id_adl: number
  id_apfd: number
  id_cd: number
  id_cj: number
  id_desercao: number
  id_fatd: number
  id_ipm: number
  id_iso: number
  id_it: number
  id_pad: number
  id_sindicancia: number
  id_sai: number
  id_proc_outros: number
  id_punicao: number
  createdAt: Date
  updatedAt: Date
}
