/* eslint-disable camelcase */
export type Sai = {
  id?: number;
  rg: string;
  cargo: string;
  nome: string;
  rg_cadastro: string;
  data: Date;
  docorigem: string;
  cdopm: string;
  cdopm_fato: string;
  cdopm_controle: string;
  opm_abreviatura: string;
  sintese_txt: string; // text
  digitador: string;
  arquivopasta: string;
  bou_ano1: string;
  bou_numero1: string;
  id_municipio: number;
  bairro: string;
  logradouro: string;
  numerodoc: string;
  motivo_principal: string;
  motivo_secundario: string;
  desc_outros: string;
  id_andamento: number;
  id_andamentocoger: number;
  sjd_ref: number;
  abertura_data: Date;
  sjd_ref_ano: number;
  vtr1_placa: string;
  vtr1_prefixo: string;
  vtr2_placa: string;
  vtr2_prefixo: string;
  relatorio1: string;
  relatorio1_data: Date;
  relatorio1_file: string;
  relatorio2: string;
  relatorio2_data: Date;
  relatorio2_file: string;
  relatorio3: string;
  relatorio3_data: Date;
  relatorio3_file: string;
  bou_ano2: string;
  bou_ano3: string;
  bou_numero2: string;
  bou_numero3: string;
};
