export * from '../opms'
export * from './adlSelects'
export * from './andamento'
export * from './andamentoCoger'
export * from './apfdSelects'
export * from './apresentacaoSelects'
export * from './boletim'
export * from './conselho'
export * from './crime'
export * from './desercaoSelects'
export * from './envolvido'
export * from './fatdSelects'
export * from './itSelects'
export * from './ocorrencia'
export * from './ofendido'
export * from './pm'
export * from './preso'
export * from './proc'
export * from './procOutrosSelects'
export * from './restricao'
export * from './resultado'
export * from './sindicanciaSelects'
export * from './sobrestamento'
export type Option = {
  value: number| string;
  label: string;
}
